# -*- coding: utf-8 -*-
"""IBS2Assign1_24AIE224.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hA2_vE2BV4bh5_CBwGativ39rx94JQki

BL.SC.U4AIE24224

JAYAVEER VENKATA SAI MADDALI

ANSWER 1:While dedicated tools like antiSMASH provide the most comprehensive analysis for identifying biosynthetic gene clusters (BGCs), Biopython can be used to build custom, lightweight scripts for detecting specific features associated with Nonribosomal Peptide Synthetases (NRPSs). This approach is useful for focused analyses, such as scanning predicted proteins for key NRPS domains.

The core idea is to use Biopython's capabilities to handle biological sequence data and parse the results from external profile Hidden Markov Model (pHMM) search tools like HMMER. The search results mention a tool called NRPS-motif-Finder, which utilizes Biopython and HMMER to identify NRPS domains based on specific motifs

QUESTION 2:
"""

amino_mass = {
    'G':57,'A':71,'S':87,'P':97,'V':99,'T':101,'C':103,
    'I':113,'L':113,'N':114,'D':115,'K':128,'Q':128,
    'E':129,'M':131,'H':137,'F':147,'R':156,'Y':163,'W':186
}

def mass(p):
    return sum(amino_mass[a] for a in p)

def linear_spectrum(p):
    prefix=[0]
    for i in range(len(p)):
        prefix.append(prefix[i]+amino_mass[p[i]])
    spec=[0]
    for i in range(len(p)):
        for j in range(i+1,len(p)+1):
            spec.append(prefix[j]-prefix[i])
    return sorted(spec)

def cyclic_spectrum(p):
    prefix=[0]
    for i in range(len(p)):
        prefix.append(prefix[i]+amino_mass[p[i]])
    total=prefix[-1]
    spec=[0]
    for i in range(len(p)):
        for j in range(i+1,len(p)+1):
            spec.append(prefix[j]-prefix[i])
            if i>0 and j<len(p):
                spec.append(total-(prefix[j]-prefix[i]))
    return sorted(spec)

def expand(peptides):
    return [p+a for p in peptides for a in amino_mass]

def brute_force(spectrum):
    parent=max(spectrum)
    peptides=['']
    answer=[]
    while peptides:
        peptides=expand(peptides)
        new=[]
        for p in peptides:
            m=mass(p)
            if m==parent:
                if cyclic_spectrum(p)==spectrum:
                    answer.append(p)
            elif m<parent:
                if all(x in spectrum for x in linear_spectrum(p)):
                    new.append(p)
        peptides=new
    return answer

spectrum = [0,113,114,128,129,227,242,242,257,355,356,370,371,484]

result = brute_force(spectrum)

print("Cyclopeptide sequence(s):")
for r in result:
    print(r)