# -*- coding: utf-8 -*-
"""IBS_ASSIGNMENTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kL_B9I8geEIc8a1b5blnvjG8vVmh3AwP

IBS ASSIGNMENT

BRUTE FORCE
"""

amino_mass = {
    'G':57,'A':71,'S':87,'P':97,'V':99,'T':101,'C':103,
    'I':113,'L':113,'N':114,'D':115,'K':128,'Q':128,
    'E':129,'M':131,'H':137,'F':147,'R':156,'Y':163,'W':186
}

def mass(p):
    return sum(amino_mass[a] for a in p)

def linear_spectrum(p):
    prefix=[0]
    for i in range(len(p)):
        prefix.append(prefix[i]+amino_mass[p[i]])
    spec=[0]
    for i in range(len(p)):
        for j in range(i+1,len(p)+1):
            spec.append(prefix[j]-prefix[i])
    return sorted(spec)

def cyclic_spectrum(p):
    prefix=[0]
    for i in range(len(p)):
        prefix.append(prefix[i]+amino_mass[p[i]])
    total=prefix[-1]
    spec=[0]
    for i in range(len(p)):
        for j in range(i+1,len(p)+1):
            spec.append(prefix[j]-prefix[i])
            if i>0 and j<len(p):
                spec.append(total-(prefix[j]-prefix[i]))
    return sorted(spec)

def expand(peptides):
    return [p+a for p in peptides for a in amino_mass]

def brute_force(spectrum):
    parent=max(spectrum)
    peptides=['']
    answer=[]
    while peptides:
        peptides=expand(peptides)
        new=[]
        for p in peptides:
            m=mass(p)
            if m==parent:
                if cyclic_spectrum(p)==spectrum:
                    answer.append(p)
            elif m<parent:
                if all(x in spectrum for x in linear_spectrum(p)):
                    new.append(p)
        peptides=new
    return answer

spectrum = [0,113,114,128,129,227,242,242,257,355,356,370,371,484]

result = brute_force(spectrum)

print("Cyclopeptide sequence(s):")
for r in result:
    print(r)

"""BRANCH AND BOUND"""

aa={'g': 57,'a': 71,'s': 87,'p' :97,'v' :99,'t' :101,'c' :103,'I' :113,'l':113,'n' :114,'d' :115,'k':128,'q' :128,
'e'  :129,
'm' :131,
'h' :137,
'f' :147,
'r' :156,
'y' :163,
'w' :186,}
def mass(Peptide):
    mass=0
    for i in Peptide:
        mass+=aa[i]
    return mass


def start(seq,spectrum,aa):
    for i in spectrum:
        for k in aa:
            if aa[k]==i:
               if k in seq:
                   continue
               seq.append([k])
    return seq

def Expand(seq,Spectrum,aa):
    for i in range(0,len(seq)):
        for k in aa:
            if mass(seq[i]+[k]) in spectrum:
                seq.append(seq[i]+[k])
                seq.remove(seq[i])
    return seq



spectrum = [0,97,97,99,101,103,196,198,198,200,202,295,297,299,301,394,396,398,400,400,497]
ans=0
CandidatePeptides=start([],spectrum,aa)
for i in range(0,5):
    CandidatePeptides = Expand(CandidatePeptides,spectrum,aa)
for i in CandidatePeptides:
    max_count = max(i.count(element) for element in set(i))
    print(max_count)
    if max_count>=3:
        continue
    else:
        ans=i
print(ans)

"""LEADERBOARD"""

!pip install BioPython
from Bio.Seq import Seq

# DNA sequence input
dna_string = (
    "GTTCCGAAAGGCTAGCGCTAGGCGCCAAGCGGCCGGTTTCCTTGGCGACGGAGAGCGCGGGAATTTTAGA"
    "TAGATTGTAATTGCGGCTGCGCGGCCGCTGCCCGTGCAGCCAGAGGATCCAGCACCTCTCTTGGGGCTTC"
    "TCCGTCCTCGGCGCTTGGAAGTACGGATCTTTTTTCTCGGAGAAAAGTTCACTGGAACTGGAAGAAATGG"
)

# Convert DNA → Protein
dna_sequence_obj = Seq(dna_string)
protein_sequence = str(dna_sequence_obj.translate(to_stop=False)).replace("*", "")

print("Protein Sequence:")
print(protein_sequence)

amino_acid_masses = {
    'A': 89,  'R': 174, 'N': 132, 'D': 133, 'C': 121,
    'Q': 146, 'E': 147, 'G': 75,  'H': 155, 'I': 131,
    'L': 131, 'K': 146, 'M': 149, 'F': 165, 'P': 115,
    'S': 105, 'T': 119, 'W': 204, 'Y': 181, 'V': 117
}

peptide_length = 4

def generate_leaderboard(protein_seq, peptide_length, top_n):
    peptide_list = []

    for index in range(len(protein_seq) - peptide_length + 1):
        current_peptide = protein_seq[index:index + peptide_length]
        total_mass = sum(amino_acid_masses[aa] for aa in current_peptide)
        peptide_list.append((current_peptide, total_mass))

    peptide_list.sort(key=lambda item: item[1], reverse=True)
    return peptide_list[:top_n]

print("Leaderboard Top 5:")
for peptide in generate_leaderboard(protein_sequence, peptide_length, 5):
    print(peptide)